### ISSUE TITLE
CRITICAL:root:cannot determine region size; use 4-item box

### ISSUE THREAD

**Issue by rbarber68** [sibson/vncdotool#104]
Example:
vncdo -s vncservername capture screen.png

Description:
When I call the  "capture" function I'm getting the following error related to PIL.
I'm getting the error on Win10(Python64), Win7(Python64) and Ubuntu 16.04.
Can someone tell me a "working" OS and Python version? 

Error:
CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\internet\tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "e:\Anaconda3\envs\py36\lib\site-packages\twisted\internet\tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "e:\Anaconda3\envs\py36\lib\site-packages\vncdotool\rfb.py", line 482, in dataReceived
    self._handler()
  File "e:\Anaconda3\envs\py36\lib\site-packages\vncdotool\rfb.py", line 491, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "e:\Anaconda3\envs\py36\lib\site-packages\vncdotool\rfb.py", line 270, in _handleRectangle
    self._handleDecodeDesktopSize(width, height)
  File "e:\Anaconda3\envs\py36\lib\site-packages\vncdotool\rfb.py", line 461, in _handleDecodeDesktopSize
    self.updateDesktopSize(width, height)
  File "e:\Anaconda3\envs\py36\lib\site-packages\vncdotool\client.py", line 420, in updateDesktopSize
    new_screen.paste(self.screen, (0, 0))
  File "e:\Anaconda3\envs\py36\lib\site-packages\PIL\Image.py", line 1331, in paste
    "cannot determine region size; use 4-item box"
builtins.ValueError: cannot determine region size; use 4-item box

CRITICAL:root:cannot determine region size; use 4-item box

**Comment by sibson** [comment]
vncdotool is tested using the following requirements, https://github.com/sibson/vncdotool/blob/master/requirements.txt

**Comment by Kochise** [comment]
Get same error with :

```bash
C:\Program Files\Spyder\Python>python -m pip list
Package                           Version
--------------------------------- ------------
Pillow                            8.3.2
pip                               21.3.1
Twisted                           21.7.0
vncdotool                         0.11.2
zope.interface                    5.4.0

C:\Program Files\Spyder\Python>
```
