### ISSUE TITLE
 unsupported operand type(s) for &: 'str' and 'int'

### ISSUE THREAD

**Issue by Nick2253** [sibson/vncdotool#116]
I'm running into a problem with the __String_to_Bitlist function in pyDes.py.  I'm assuming this is a Python2 vs Python3 issue, but somewhere along the way, the data passing into __String_to_Bitlist is not being cleaned/prepared properly.

To try and troubleshoot this, I traced the data back through to the _guardAgainstUnicode function, and I added a print line to see what I'm dealing with (the first line in the error below).  To me, it looks like we've got unicode characters, and the data is not adequately being guarded against, and I'm not sure what else to fix it.

(My line numbers might be off, because I've been adding comments and debug statements to try and trace back where the issue was coming from.  Also, the password I'm using is just 'password', so nothing sensitive here).

```
Guarding against:  ['\x0e', '\x86', 'Î', 'Î', 'î', 'ö', 'N', '&']
Unhandled Error
Traceback (most recent call last):
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "c:\python\python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 482, in dataReceived
    self._handler()
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 491, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 175, in _handleVNCAuth
    self.vncRequestPassword()
  File "c:\python\python36-32\lib\site-packages\vncdotool\command.py", line 50, in vncRequestPassword
    self.sendPassword(self.factory.password)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 181, in sendPassword
    des = RFBDes(pw)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 410, in __init__
    self.setKey(key)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 635, in setKey
    super(RFBDes, self).setKey(newkey)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 415, in setKey
    self.__create_sub_keys()
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 463, in __create_sub_keys
    key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 429, in __String_to_BitList
    if ch & (1 << i) != 0:
builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "c:\python\python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 482, in dataReceived
    self._handler()
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 491, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 175, in _handleVNCAuth
    self.vncRequestPassword()
  File "c:\python\python36-32\lib\site-packages\vncdotool\command.py", line 50, in vncRequestPassword
    self.sendPassword(self.factory.password)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 181, in sendPassword
    des = RFBDes(pw)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 410, in __init__
    self.setKey(key)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 635, in setKey
    super(RFBDes, self).setKey(newkey)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 415, in setKey
    self.__create_sub_keys()
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 463, in __create_sub_keys
    key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 429, in __String_to_BitList
    if ch & (1 << i) != 0:
builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'

CRITICAL:root:unsupported operand type(s) for &: 'str' and 'int'
```

**Comment by Nick2253** [comment]
And here's the error with the default pyDes.py:

```
Unhandled Error
Traceback (most recent call last):
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "c:\python\python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 482, in dataReceived
    self._handler()
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 491, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 175, in _handleVNCAuth
    self.vncRequestPassword()
  File "c:\python\python36-32\lib\site-packages\vncdotool\command.py", line 50, in vncRequestPassword
    self.sendPassword(self.factory.password)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 181, in sendPassword
    des = RFBDes(pw)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 409, in __init__
    self.setKey(key)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 635, in setKey
    super(RFBDes, self).setKey(newkey)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 414, in setKey
    self.__create_sub_keys()
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 462, in __create_sub_keys
    key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 428, in __String_to_BitList
    if ch & (1 << i) != 0:
builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\python\python36-32\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "c:\python\python36-32\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 205, in doRead
    return self._dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\twisted\internet\tcp.py", line 211, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 482, in dataReceived
    self._handler()
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 491, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 175, in _handleVNCAuth
    self.vncRequestPassword()
  File "c:\python\python36-32\lib\site-packages\vncdotool\command.py", line 50, in vncRequestPassword
    self.sendPassword(self.factory.password)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 181, in sendPassword
    des = RFBDes(pw)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 409, in __init__
    self.setKey(key)
  File "c:\python\python36-32\lib\site-packages\vncdotool\rfb.py", line 635, in setKey
    super(RFBDes, self).setKey(newkey)
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 414, in setKey
    self.__create_sub_keys()
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 462, in __create_sub_keys
    key = self.__permutate(des.__pc1, self.__String_to_BitList(self.getKey()))
  File "c:\python\python36-32\lib\site-packages\vncdotool\pyDes.py", line 428, in __String_to_BitList
    if ch & (1 << i) != 0:
builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'

CRITICAL:root:unsupported operand type(s) for &: 'str' and 'int'
```

**Comment by Nick2253** [comment]
This is fixed by https://github.com/sibson/vncdotool/pull/117
