### ISSUE TITLE
ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by alex2304** [sibson/vncdotool#151]
Software:
- VNC server and version unknown
- vncdotool==0.12.1

Reproduce:
- Connect to the server via VNC Viewer software, with "hight quality" enabled in settings
- Inside python program, use own VNCDoToolFactory with **shared=True**
- Try to connect using vncdotool - and it should appear

The following error is raised:
```
  File "/lib/python3.6/site-packages/vncdotool/rfb.py", line 441, in _handleDecodeHextileSubrect
    subrects = ord(block[pos])
builtins.TypeError: ord() expected string of length 1, but int found
```

Appreciate any help 🙏 

Detailed traceback (with DEBUG level):
```
2019-05-07 17:57:56,601 - twisted - INFO - Using protocol version 3.300
Using protocol version 3.300
Unhandled Error
Traceback (most recent call last):
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 527, in dataReceived
    self._handler()
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 536, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 441, in _handleDecodeHextileSubrect
    subrects = ord(block[pos])
builtins.TypeError: ord() expected string of length 1, but int found

2019-05-07 17:57:58,297 - twisted - CRITICAL - Unhandled Error
Traceback (most recent call last):
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 527, in dataReceived
    self._handler()
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 536, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 441, in _handleDecodeHextileSubrect
    subrects = ord(block[pos])
builtins.TypeError: ord() expected string of length 1, but int found

Unhandled Error
Traceback (most recent call last):
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 527, in dataReceived
    self._handler()
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 536, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/rfb.py", line 441, in _handleDecodeHextileSubrect
    subrects = ord(block[pos])
builtins.TypeError: ord() expected string of length 1, but int found

2019-05-07 17:57:58,298 - twisted - INFO - Stopping factory <src.client.VNCClientFactory object at 0x118fd4dd8>
Stopping factory <src.client.VNCClientFactory object at 0x118fd4dd8>

Traceback (most recent call last):
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/api.py", line 103, in proxy_call
    result = self.queue.get(timeout=self._timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/queue.py", line 172, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tk/venv/my-project/lib/python3.6/site-packages/vncdotool/api.py", line 105, in proxy_call
    raise TimeoutError("Timeout while waiting for client response")
TimeoutError: Timeout while waiting for client response
```

**Comment by alex2304** [comment]
Figured out that it happens when using `HEXTILE_ENCODING`.

If I try to use any other encoding except `RAW_ENCODING` and `HEXTILE_ENCODING` - server responds with unknown encoding type in `_handleRectangle`.

**Comment by c001c0de** [comment]
Should be fixed by https://github.com/sibson/vncdotool/pull/164 (merged as 521e0ed905f7232a7331259c47aad4d393b0987a)

**Comment by guicho271828** [comment]
@sibson now you can close this issue

**Comment by sibson** [comment]
thanks @guicho271828, feel free to close them yourself too.

**Comment by guicho271828** [comment]
I can't close them by myself, only the repo owner and the issue submitter can.
