### ISSUE TITLE
CRITICAL:root:unsupported operand type(s) for &: 'str' and 'int'

### ISSUE THREAD

**Issue by nandish017** [sibson/vncdotool#172]
Have you included the following information?

 -  Tight VNC 2.8.27
 -  Latest vncdotool
 - Installed vncdotool by following the steps mentioned in https://vncdotool.readthedocs.io/en/latest/install.html#windows
I am able to connect to the mentioned IP, when i give for the password for vncpassword I get the following error:

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\internet\tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\twisted\internet\tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\rfb.py", line 685, in dataReceived
    self._handler()
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\rfb.py", line 694, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\rfb.py", line 255, in _handleVNCAuth
    self.vncRequestPassword()
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\command.py", line 52, in vncRequestPassword
    self.sendPassword(self.factory.password)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\rfb.py", line 261, in sendPassword
    des = RFBDes(pw)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\pyDes.py", line 410, in __init__
    self.setKey(key)
  File "c:\users\appdata\local\programs\python\python3.8\lib\site-packages\vncdotool\rfb.py", line 835, in setKey
    if bsrc & (1 << i):
builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'

CRITICAL:root:unsupported operand type(s) for &: 'str' and 'int'

**Comment by ponty** [comment]
This is the problem in rfb.py:
```python
# Python3 compatibility replacement for ord(str) as ord(byte)
if not isinstance(b' ', str):
    def ord(x): return x
```
Testing it in Python3 console:

```pycon
>>> ord('1')
49
>>> if not isinstance(b' ', str):
...     def ord(x): return x
... 
>>> ord('1')
'1'
```
`ord('1')` should be int.

**Comment by ponty** [comment]
Test case for this bug in #177

**Comment by mmomrk** [comment]
As a temporary workaround one may redefine ord() in rfb.py. Here's the code, pasted it as a quote; parser refused to accept it in the code block. So add indentation yourself everywhere except the first line:

> def ord(ch):
    hard = {' ': 32,
            '0': 48,
            '1': 49,
            '2': 50,
            '3': 51,
            '4': 52,
            '5': 53,
            '6': 54,
            '7': 55,
            '8': 56,
            '9': 57,
            'a': 97,
            'b': 98,
            'c': 99,
            'd': 100,
            'e': 101,
            'f': 102,
            'g': 103,
            'h': 104,
            'i': 105,
            'j': 106,
            'k': 107,
            'l': 108,
            'm': 109,
            'n': 110,
            'o': 111,
            'p': 112,
            'q': 113,
            'r': 114,
            's': 115,
            't': 116,
            'u': 117,
            'v': 118,
            'w': 119,
            'x': 120,
            'y': 121,
            'z': 122,
            'A': 65,
            'B': 66,
            'C': 67,
            'D': 68,
            'E': 69,
            'F': 70,
            'G': 71,
            'H': 72,
            'I': 73,
            'J': 74,
            'K': 75,
            'L': 76,
            'M': 77,
            'N': 78,
            'O': 79,
            'P': 80,
            'Q': 81,
            'R': 82,
            'S': 83,
            'T': 84,
            'U': 85,
            'V': 86,
            'W': 87,
            'X': 88,
            'Y': 89,
            'Z': 90,
            '!': 33,
            '"': 34,
            '#': 35,
            '$': 36,
            '%': 37,
            '&': 38,
            '\'': 39,
            '(': 40,
            ')': 41,
            '*': 42,
            '+': 43,
            ',': 44,
            '-': 45,
            '.': 46,
            '/': 47,
            ':': 58,
            ';': 59,
            '<': 60,
            '=': 61,
            '>': 62,
            '?': 63,
            '@': 64,
            '[': 91,
            '\\\\': 92,
            ']': 93,
            '^': 94,
            '_': 95,
            '`': 96,
            '{': 123,
            '|': 124,
            '}': 125,
            '~': 126}
    return hard[ch]


Works for me

**Comment by guicho271828** [comment]
@sibson now you can close this issue

**Comment by Kub-AT** [comment]
@sibson Will you provide a release (PyPI package with that fix ?)
