### ISSUE TITLE
builtins.ValueError: Invalid initialization option

### ISSUE THREAD

**Issue by marcobazzani** [sibson/vncdotool#183]
Have you included the following information?

 - [x] VNC server and version
Xvnc TigerVNC 1.11.0 - built Sep  8 2020 12:27:03
Copyright (C) 1999-2020 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12001000, The X.Org Foundation

 - [x] vncdotool version
1.0.0
 - [x] steps to reproduce
vncdo -v -s localhost::39737 -p xxxx type "ls"

output:

```
INFO:root:connecting to localhost:39737
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory object at 0x7f2bbc2ac668>
Unhandled Error
Traceback (most recent call last):
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
    self._connectDone()
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/tcp.py", line 641, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/base.py", line 1157, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/protocol.py", line 140, in buildProtocol
    p = self.protocol()
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vncdotool/rfb.py", line 171, in __init__
    self._zlib_stream = zlib.decompressobj(0)
builtins.ValueError: Invalid initialization option

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/posixbase.py", line 619, in _doReadOrWrite
    why = selectable.doWrite()
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/tcp.py", line 627, in doConnect
    self._connectDone()
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/tcp.py", line 641, in _connectDone
    self.protocol = self.connector.buildProtocol(self.getPeer())
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/base.py", line 1157, in buildProtocol
    return self.factory.buildProtocol(addr)
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/protocol.py", line 140, in buildProtocol
    p = self.protocol()
  File "/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vncdotool/rfb.py", line 171, in __init__
    self._zlib_stream = zlib.decompressobj(0)
builtins.ValueError: Invalid initialization option

CRITICAL:root:An error occurred while connecting: [Failure instance: Traceback: <class 'ValueError'>: Invalid initialization option
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/log.py:86:callWithContext
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/posixbase.py:627:_doReadOrWrite
--- <exception caught here> ---
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/posixbase.py:619:_doReadOrWrite
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/tcp.py:627:doConnect
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/tcp.py:641:_connectDone
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/base.py:1157:buildProtocol
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/twisted/internet/protocol.py:140:buildProtocol
/home/mbazzan/.pyenv/versions/3.6.8/lib/python3.6/site-packages/vncdotool/rfb.py:171:__init__
].
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory object at 0x7f2bbc2ac668>
INFO:twisted:Main loop terminated.
```

server is running as:

```
ec2-user  6950  0.0  0.0  83936 41260 ?        S<   09:40   0:00 /usr/bin/Xvnc :1 --acceptcuttext=1 --acceptkeyevents=1 --acceptpointerevents=1 --allowoverride= --localhost --log=*:stdout:90 --maxconnectiontime=0 --maxdisconnectiontime=0 --maxidletime=0 --sendcuttext=1 --zliblevel=9 -nolisten tcp -rfbport 1010 -securitytypes vncauth,tlsvnc -auth /home/ec2-user/.Xauthority -desktop master.hoverboard.amazon.com:1 (ec2-user) -fp catalogue:/etc/X11/fontpath.d -geometry 1024x768 -pn -rfbauth /home/ec2-user/.vnc/passwd -rfbwait 30000
```

**Comment by marcobazzani** [comment]
https://github.com/sibson/vncdotool/pull/184

**Comment by marcobazzani** [comment]
#185 fixes this tested

**Comment by sibson** [comment]
This seems to be related to an outdated zlip version, per #186.
