### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'TLS_METHOD'

### ISSUE THREAD

**Issue by Guation** [sibson/vncdotool#290]
Please include the following information:

**vncdotool version**

vncdotool         1.2.0

**VNC server and version**

none

**Steps to reproduce**

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vncdotool import api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/vncdotool/api.py", line 15, in <module>
    from twisted.internet import reactor
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/default.py", line 55, in <module>
    install = _getInstallFunction(platform)
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/default.py", line 43, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/epollreactor.py", line 19, in <module>
    from twisted.internet import posixbase
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/posixbase.py", line 16, in <module>
    from twisted.internet import error, tcp, udp
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/tcp.py", line 40, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/_newtls.py", line 18, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory
  File "/usr/local/lib/python3.9/dist-packages/twisted/protocols/tls.py", line 48, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/_sslverify.py", line 1829, in <module>
    defaultCiphers = OpenSSLAcceptableCiphers.fromOpenSSLCipherString(
  File "/usr/local/lib/python3.9/dist-packages/twisted/internet/_sslverify.py", line 1808, in fromOpenSSLCipherString
    SSL.TLS_METHOD,
AttributeError: module 'OpenSSL.SSL' has no attribute 'TLS_METHOD'
>>> 
```

**Expected result**

no error

**Which erroneous result did you get instead**

AttributeError: module 'OpenSSL.SSL' has no attribute 'TLS_METHOD'

**Additional information**

RaspberryPi 4B, Raspberry Pi OS (64-bit) with desktop (bullseye).

pyOpenSSL         20.0.1

**Comment by pmhahn** [comment]
This is not a bug in vnctool, but in OpenSSL and/or its Python binding. Looks like your version of it was compiled against an older/newer version of the C library which is now installed on your RasPi.

Google for `AttributeError: module 'OpenSSL.SSL' has no attribute 'TLS_METHOD'` and you will find https://stackoverflow.com/questions/73859249/attributeerror-module-openssl-ssl-has-no-attribute-sslv3-method, which might fix it for you.

**Comment by Guation** [comment]
I reinstalled the system to bookworm, and this problem does not exist in the venv of Python 3.11.2. I found that the pyopenssl library does not exist in the venv, which may be due to compatibility issues.
