### ISSUE TITLE
Exception with Pillow 3.1.1: fromstring() has been removed. Please call frombytes() instead.

### ISSUE THREAD

**Issue by vdmit** [sibson/vncdotool#62]
I've installed vncdotool using pip on fresh CentOS and faced with following exception doing capture via command line:

```
CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
    return self._dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 467, in dataReceived
    self._handler()
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 476, in _handleExpected
    self._expected_handler(block, *self._expected_args, **self._expected_kwargs)
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 271, in _handleDecodeRAW
    self.updateRectangle(x, y, width, height, block)
  File "/usr/lib/python2.7/site-packages/vncdotool/client.py", line 369, in updateRectangle
    update = Image.fromstring('RGB', size, data, 'raw', 'RGBX')
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2063, in fromstring
    "Please call frombytes() instead.")
exceptions.Exception: fromstring() has been removed. Please call frombytes() instead.

```

My `pip freeze` output contains:
```
Pillow==3.1.1
Twisted==15.5.0
vncdotool==0.9.0
```

I've tried to patch `client.py` by direct replace of `fromstring()` to `frombytes()` in 3 places. And it worked OK, at least on capture command. I'm not sure that this is correct patch, but it seems to be a trivial function rename in new version of `pillow`.

**Comment by sibson** [comment]
The issue should be fixed in master, https://github.com/sibson/vncdotool/commit/96611bf746eba30254415ba9d4057beadb8c88f4 <https://github.com/sibson/vncdotool/commit/96611bf746eba30254415ba9d4057beadb8c88f4>

**Comment by vdmit** [comment]
Oops, I've missed it. Thanks a lot.

**Comment by godp1301** [comment]
@sibson Can you release a new version on pypi?

**Comment by sibson** [comment]
@godp1301 done, https://pypi.python.org/pypi/vncdotool/0.10.0
