### ISSUE TITLE
CRITICAL:root:unsupported operand type(s) for %: 'bytes' and 'tuple'

### ISSUE THREAD

**Issue by ados1991** [sibson/vncdotool#84]
Hi, i install the last version vncdotool and i have this while i am testing on (python3.7/centos7) machine

What can i do for fix the problem ?

Thanks

vncdo -s 172.16.100.41 capture screen.png

Unhandled Error
Traceback (most recent call last):
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/var/www/commercial/env/lib/python3.4/site-packages/vncdotool/rfb.py", line 474, in dataReceived
    self._handler()
  File "/var/www/commercial/env/lib/python3.4/site-packages/vncdotool/rfb.py", line 143, in _handleInitial
    b"RFB %03d.%03d\n" % (int(parts[0]), int(parts[1])))
builtins.TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/var/www/commercial/env/lib/python3.4/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/var/www/commercial/env/lib/python3.4/site-packages/vncdotool/rfb.py", line 474, in dataReceived
    self._handler()
  File "/var/www/commercial/env/lib/python3.4/site-packages/vncdotool/rfb.py", line 143, in _handleInitial
    b"RFB %03d.%03d\n" % (int(parts[0]), int(parts[1])))
builtins.TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

CRITICAL:root:unsupported operand type(s) for %: 'bytes' and 'tuple'

**Comment by neerajvashistha** [comment]
same here any updates :-(

**Comment by sibson** [comment]
That looks like a python3 vs python2 issue.  I'm unlikely to have time to debug further in the near term.  This [document](https://docs.python.org/3/howto/pyporting.html) might be helpful if you'd like to investigate.

**Comment by ados1991** [comment]
Thanks

**Comment by jamtwister** [comment]
I agree Marc, looks like a py3 vs py2 issue.
And proably you do not use RFB version 3.3.

If you post the content of the variable "version_server" (line 131) I will look for a solution.

**Comment by muzhig** [comment]
Hi, faced this and other Py3 issues today, does anybody know which python/library version is stable?

**Comment by scherma** [comment]
I am still experiencing the issue:

Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.4/dist-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.4/dist-packages/vncdotool/rfb.py", line 482, in dataReceived
    self._handler()
  File "/usr/local/lib/python3.4/dist-packages/vncdotool/rfb.py", line 144, in _handleInitial
    bytes(b"RFB %03d.%03d\n" % (int(parts[0]), int(parts[1]))))
builtins.TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

triggered by:
   client.keyPress('lsuper')

python 3.4, vncdotool 0.11.2, Debian Jessie

**Comment by FedericoCeratto** [comment]
The issue affects python 3.4.1 on SLES as well. Any workaround other than upgrading Python?
