### ISSUE TITLE
Cannot run on mac osx El Capitain

### ISSUE THREAD

**Issue by mihai-satmarean** [sibson/vncdotool#93]
Traceback (most recent call last):
  File "/usr/local/bin/vncdo", line 9, in <module>
    load_entry_point('vncdotool==0.10.0', 'console_scripts', 'vncdo')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/vncdotool/command.py", line 18, in <module>
    from twisted.internet import reactor, protocol
  File "/Library/Python/2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Library/Python/2.7/site-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Library/Python/2.7/site-packages/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Library/Python/2.7/site-packages/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Library/Python/2.7/site-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Library/Python/2.7/site-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/Library/Python/2.7/site-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/Library/Python/2.7/site-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/Library/Python/2.7/site-packages/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

Thank you!

**Comment by sibson** [comment]
Looks like versionitis of some type between Twisted, Python and the libssl being used. Perhaps using virtualenv would help narrow down the problem.

**Comment by mihai-satmarean** [comment]
Hi, I would do whatever to help, I am not very experienced with virtualenv.

Pe 10 apr. 2017, la 05:51, Marc Sibson <notifications@github.com> a scris:

**Comment by sibson** [comment]
This might be helpful, http://docs.python-guide.org/en/latest/dev/virtualenvs/
