### ISSUE TITLE
exceptions.TypeError: str() takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by tmp6154** [sibson/vncdotool#97]
For python2, vncdotool fails

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 483, in dataReceived
    self._handler()
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 145, in _handleInitial
    bytes("RFB %03d.%03d\n" % (int(parts[0]), int(parts[1])), 'ascii'))
exceptions.TypeError: str() takes at most 1 argument (2 given)

CRITICAL:twisted:Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 208, in doRead
    return self._dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 214, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 483, in dataReceived
    self._handler()
  File "/usr/lib/python2.7/site-packages/vncdotool/rfb.py", line 145, in _handleInitial
    bytes("RFB %03d.%03d\n" % (int(parts[0]), int(parts[1])), 'ascii'))
exceptions.TypeError: str() takes at most 1 argument (2 given)
```

The problem there is this line of code:

bytes("RFB %03d.%03d\n" % (int(parts[0]), int(parts[1])), 'ascii'))

It's fine for Python 3, but under Python 2, bytes is an alias for str, and so it cannot accept the encoding, so, vncdotool crashes with exception.

**Comment by tmp6154** [comment]
https://github.com/sibson/vncdotool/commit/659a9e327d511e7de4375122cefb3ac46f22daeb

This commit introduced breakage.

**Comment by tmp6154** [comment]
Can you, please, release the update of vncdotool on pip? Like, a minor update 0.11.1. Because current release is completely broken for Python 2.

**Comment by sibson** [comment]
yup, done now. Thanks for the reminder.
